data:
  path_to_data: ./dataset
  output_dir: ./results
  logging_dir: ./logs
  logging_steps: 5000
  save_steps: 5000

model:
  model_name: EleutherAI/gpt-neo-125M
  max_seq_length: 2048
  learning_rate: 2e-5
  batch_size: 1
  num_epochs: 1
  num_warmup_steps: 0 
  weight_decay: 0.01